Домашнее задание - Урок 1. Основные понятия и структуры PyTorch
1. Создайте случайный FloatTensor размера 3x4x5
2. Выведите его форму (shape)
3. Приведите его к форме 6х10
4. Создайте случайный IntTensor размера 10
5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 7. 
7. Подсказка: .dot может не подойти
8. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
9. Создайте единичный тензор размера 5x6
10. Переведите его в формат numpy

In [ ]:
import torch

In [ ]:
#  1. Создайте случайный FloatTensor размера 3x4x5

a = torch.randn(3, 4, 5)
a

tensor([[[ 0.0320,  0.7657, -0.5646, -0.0457, -0.0306],
         [-2.2976, -0.0663, -1.0038, -0.7269,  0.4516],
         [-1.1910, -0.0668,  0.4771, -1.7447,  0.8762],
         [ 1.0128, -0.8695, -0.9814,  0.9360,  1.3334]],

        [[-0.7126,  0.9151,  0.3364,  0.9942, -0.1030],
         [-0.0192, -0.0288,  0.4773,  0.4666,  0.1777],
         [-0.5070,  2.3725, -0.7155, -1.1210,  0.9886],
         [ 1.0594,  2.9766, -0.0824, -0.9024,  2.2033]],

        [[ 0.6034,  0.8609, -0.2657,  1.0732, -1.0449],
         [ 0.3290,  1.3731,  0.5070,  0.2875, -1.2769],
         [-0.8184, -0.5324, -0.9111,  0.3628,  0.0801],
         [-0.8082, -0.2755,  1.5886, -1.2291, -2.8712]]])

In [ ]:
# 2. Выведите его форму (shape)
print('Тензор a: ', a.type(), a.shape)

Тензор a:  torch.FloatTensor torch.Size([3, 4, 5])


In [ ]:
# 3. Приведите его к форме 6 X 10
a = torch.reshape(a, [6, 10])
a, a.shape

(tensor([[ 0.0320,  0.7657, -0.5646, -0.0457, -0.0306, -2.2976, -0.0663, -1.0038,
          -0.7269,  0.4516],
         [-1.1910, -0.0668,  0.4771, -1.7447,  0.8762,  1.0128, -0.8695, -0.9814,
           0.9360,  1.3334],
         [-0.7126,  0.9151,  0.3364,  0.9942, -0.1030, -0.0192, -0.0288,  0.4773,
           0.4666,  0.1777],
         [-0.5070,  2.3725, -0.7155, -1.1210,  0.9886,  1.0594,  2.9766, -0.0824,
          -0.9024,  2.2033],
         [ 0.6034,  0.8609, -0.2657,  1.0732, -1.0449,  0.3290,  1.3731,  0.5070,
           0.2875, -1.2769],
         [-0.8184, -0.5324, -0.9111,  0.3628,  0.0801, -0.8082, -0.2755,  1.5886,
          -1.2291, -2.8712]]),
 torch.Size([6, 10]))

In [ ]:
#  4. Создайте случайный IntTensor размера 10

b = torch.IntTensor(10)
b.type(), b

('torch.IntTensor',
 tensor([        0,         1,         1,         0,         0,         0,
                49,         0, 128959136,         0], dtype=torch.int32))

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[ 0.0000e+00,  7.6567e-01, -5.6459e-01, -0.0000e+00, -0.0000e+00,
         -0.0000e+00, -3.2485e+00, -0.0000e+00, -9.3738e+07,  0.0000e+00],
        [-0.0000e+00, -6.6817e-02,  4.7707e-01, -0.0000e+00,  0.0000e+00,
          0.0000e+00, -4.2605e+01, -0.0000e+00,  1.2071e+08,  0.0000e+00],
        [-0.0000e+00,  9.1513e-01,  3.3637e-01,  0.0000e+00, -0.0000e+00,
         -0.0000e+00, -1.4096e+00,  0.0000e+00,  6.0175e+07,  0.0000e+00],
        [-0.0000e+00,  2.3725e+00, -7.1547e-01, -0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.4585e+02, -0.0000e+00, -1.1638e+08,  0.0000e+00],
        [ 0.0000e+00,  8.6089e-01, -2.6571e-01,  0.0000e+00, -0.0000e+00,
          0.0000e+00,  6.7280e+01,  0.0000e+00,  3.7072e+07, -0.0000e+00],
        [-0.0000e+00, -5.3240e-01, -9.1114e-01,  0.0000e+00,  0.0000e+00,
         -0.0000e+00, -1.3502e+01,  0.0000e+00, -1.5851e+08, -0.0000e+00]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
a @ a.T

tensor([[ 7.9322, -1.6683, -0.2463,  1.3273, -1.3299, -0.0610],
        [-1.6683, 10.8613, -0.6658,  3.5847, -6.4825, -7.1040],
        [-0.2463, -0.6658,  2.9357,  0.9008,  1.5463, -0.1602],
        [ 1.3273,  3.5847,  0.9008, 24.2900,  1.0119, -7.5481],
        [-1.3299, -6.4825,  1.5463,  1.0119,  7.3829,  3.0696],
        [-0.0610, -7.1040, -0.1602, -7.5481,  3.0696, 14.9286]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75*t в точке (1, 0.5, 2)

x = torch.tensor(1.0, requires_grad = True) 
z = torch.tensor(0.5, requires_grad = True) 
t = torch.tensor(2.0, requires_grad = True) 

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() #считаем производную по всем переменным

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) #частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [ ]:
# 8. Создайте единичный тензор размера 5x6
e = torch.ones([5, 6])
e, e.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]))

In [ ]:
# 9. Переведите его в формат numpy
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)